sudo: required

services:
  - docker

before_install:
  - docker build -t adarsh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adarsh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-440744215961"
  bucket_path: "docker-react"
  on:
    branch: master
